version: '3.7'

services:

######################################################
#  KEYCLOAK
######################################################   
  postgresql-kc:
    container_name: postgresql-kc
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=${PGPASSWORD_KEYCLOAK}
      - POSTGRESQL_DATABASE=bitnami_keycloak
    networks:
      - kc-net
    volumes:
      - 'postgresql_kc:/bitnami/postgresql'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U bn_keycloak -d ${PGPASSWORD_KEYCLOAK}" ]

  keycloak:
    image: docker.io/bitnami/keycloak:21
    environment:
      - KEYCLOAK_LOG_LEVEL=DEBUG
#      - KEYCLOAK_HOSTNAME=auth2.ukserp.ac.uk
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=${KeyCloakAdminUser}
      - KEYCLOAK_ADMIN_PASSWORD=${KeyCloakAdminPassword}
      - KEYCLOAK_MANAGEMENT_USER=hirumanager
      - KEYCLOAK_MANAGEMENT_PASSWORD=sgs56435FGSd9
      - KEYCLOAK_ENABLE_STATISTICS=true
      - KEYCLOAK_DATABASE_HOST=postgresql-kc
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=${PGPASSWORD_KEYCLOAK}
      - REDIRECT_SOCKET="proxy-https"
      - PROXY_ADDRESS_FORWARDING="true"
      - KEYCLOAK_PROXY=edge
    networks:
      - kc-net
    depends_on:
        postgresql-kc:
          condition: service_healthy    
    ports:
      - "9090:8080"

######################################################
# VOLUME
######################################################
volumes:
    postgresql_kc:
      driver: local      


######################################################
# networks
######################################################      
networks:
  kc-net:
    driver: bridge